### ISSUE TITLE
Error when attempting to run commands to view default streamlit app

### ISSUE THREAD

**Issue by aditsanghvi94** [tzaffi/streamlit-cdk-fargate#1]
Hi,
I ran the steps and deployed successfully. When i navigate to my URL, this is the error I see

![image](https://user-images.githubusercontent.com/14086839/143894051-b9c6561c-2a99-418f-94aa-ff90985482a3.png)

I'm new to streamlit, could you help me figure out whats going on here? I am using the default code provided by you

**Comment by tzaffi** [comment]
This could be a timing issue. I'm closing as I'm not working on this and more than 2 years have passed. But I'll accept pull request that ameliorate. Just reopen/clone the issue and provide a fix.
